# Format: RequestClass=ResponseClass:field_request_1=field_response_1,field_request_2=field_response_2
[DEFAULT]
CreateUserRequest=CreateUserResponse:username=username,role=role
UpdateCustomerProfileResponse=CreateUserRequest:username=username,role=role
LoginUserRequest=LoginUserResponse:username=username
AccountDepositRequest=AccountDepositResponse:accountId=id
AccountTransferRequest=AccountTransferResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
CreateAccountResponse=CreateAccountResponse:id=id,accountNumber=accountNumber,balance=balance